name: iAnchor
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pytorch
  - pytest
  - black
  - scikit-image
  - torchvision
  - pip
  - pip:
      - pdoc3
      - smac
      - ConfigSpace
      - tensorflow
      - transformers
      - spacy
